export const actionButton = [
  {
    label: "Resume",
    img: "/N3tk1Kv/Screenshot-2024-03-04-at-01-37-24.png",
  },
  {
    label: "Stop",
    img: "/Zgv2shR/Screenshot-2024-03-04-at-01-49-36.png",
  },
  {
    label: "Stop All",
    img: "/HF5thcB/Screenshot-2024-03-04-at-01-50-21.png",
  },
  {
    label: "Delete",
    img: "/Kqkz4s5/Screenshot-2024-03-04-at-01-51-02.png",
  },
  {
    label: "Options",
    img: "/BfTYPTg/Screenshot-2024-03-04-at-01-51-42.png",
  },
  {
    label: "Queues",
    img: "/wJnmDWs/Screenshot-2024-03-04-at-01-52-23.png",
  },
  {
    label: "Schedule",
    img: "/4SK644T/Screenshot-2024-03-04-at-01-53-05.png",
  },
  {
    label: "Share",
    img: "/BqHdZpj/Screenshot-2024-03-04-at-01-53-43.png",
  },
];

export const mockDataTable = [
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
  {
    id: 1,
    key: 1,
    name: "UIUXMonster",
    size: 745,
    status: "Complete",
    timeLeft: 0,
    lastModification: "2023/08/09",
  },
];
